eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      default-zone: ${EUREKA_SERVER_ADRESS:http://localhost:8761/eureka}
